import type { Metadata } from "next";
import Script from 'next/script';
import { print } from 'graphql';
// import 'bootstrap/dist/css/bootstrap.min.css';
import '../scss/global.scss';
// Phosphor Icons — CSS-only package; loaded here so the bundler resolves font URLs
// from node_modules. Uncomment additional weights as needed.
import '@phosphor-icons/web/regular';
// import '@phosphor-icons/web/bold';
// import '@phosphor-icons/web/fill';
import { gql } from '@apollo/client';
import { fetchGraphQL } from '@/lib/wp/client';
import GET_SPRITEMAP_ICONS from '@/lib/wp/queries/spritemap-icons';

// Font loading patterns:
//
// Google Fonts — use next/font/google (self-hosted, inlined, zero external request):
//   import { Inter } from 'next/font/google';
//   const inter = Inter({ subsets: ['latin'] });
//   <body className={inter.className}>
//
// Adobe Fonts (Typekit) — use the async JS embed (non-blocking):
//   Set NEXT_PUBLIC_TYPEKIT_ID=your_kit_id in .env.local
//   The Script below handles it — the preconnects in <head> open the connection early.
//
// Never use <link rel="stylesheet"> for web fonts in the <head> — it blocks first paint.
// Never use CSS @import url() for web fonts — it blocks rendering and is discovered late.

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: [
        {
            url: '/icon.ico',
            media: '(prefers-color-scheme: light)',
        },
        {
            url: '/icon.ico',
            media: '(prefers-color-scheme: dark)',
        },
    ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const typekitId = process.env.NEXT_PUBLIC_TYPEKIT_ID;

  const GET_GLOBAL_CSS = gql`
    query GetGlobalCss {
      customizerCss
      fontOptionsCss
      globalStylesCss
      customizerSettings {
        customCss
        backgroundColor
        backgroundImage
        backgroundRepeat
        backgroundPosition
        backgroundSize
        backgroundAttachment
      }
      themeHeaderOptions {
        settingsHeaderOptions {
          headerPosition
          shrinkHeader
          navbarBreakpoint
        }
      }
      themeGeneralOptions {
        settingsThemeGeneralOptions {
          removeContentContainers
        }
      }
    }
  `;

  const [cssResult, spritemapResult] = await Promise.allSettled([
    fetchGraphQL<{
      customizerCss: string | null;
      fontOptionsCss: string | null;
      globalStylesCss: string | null;
      customizerSettings: {
        customCss: string | null;
        backgroundColor: string | null;
        backgroundImage: string | null;
        backgroundRepeat: string | null;
        backgroundPosition: string | null;
        backgroundSize: string | null;
        backgroundAttachment: string | null;
      } | null;
      themeHeaderOptions: { settingsHeaderOptions: { headerPosition: string | null; shrinkHeader: boolean | null } | null } | null;
    }>(print(GET_GLOBAL_CSS)),
    fetchGraphQL<{ spritemapIcons: { spritemap: string | null; url: string | null; scss: string | null } | null }>(
      print(GET_SPRITEMAP_ICONS),
    ),
  ]);

  const cssData = cssResult.status === 'fulfilled' ? (cssResult.value as any)?.data : null;
  const spritemapSvg: string | null = spritemapResult.status === 'fulfilled'
    ? ((spritemapResult.value as any)?.data?.spritemapIcons?.spritemap ?? null)
    : null;

  const bgSettings = cssData?.customizerSettings;
  const customBackgroundCss = (bgSettings?.backgroundImage || bgSettings?.backgroundColor)
    ? [
        'body.custom-background {',
        bgSettings.backgroundColor ? `  background-color: #${bgSettings.backgroundColor.replace(/^#/, '')};` : null,
        bgSettings.backgroundImage ? `  background-image: url("${bgSettings.backgroundImage}");` : null,
        bgSettings.backgroundImage ? `  background-position: ${bgSettings.backgroundPosition ?? 'left top'};` : null,
        bgSettings.backgroundImage ? `  background-size: ${bgSettings.backgroundSize ?? 'auto'};` : null,
        bgSettings.backgroundImage ? `  background-repeat: ${bgSettings.backgroundRepeat ?? 'repeat'};` : null,
        bgSettings.backgroundImage ? `  background-attachment: ${bgSettings.backgroundAttachment ?? 'scroll'};` : null,
        '}',
      ].filter(Boolean).join('\n')
    : null;

  const globalCss = [
    cssData?.globalStylesCss,
    cssData?.customizerCss,
    cssData?.fontOptionsCss,
    customBackgroundCss,
    cssData?.customizerSettings?.customCss,
  ].filter(Boolean).join('\n') || null;

  const headerOpts = (cssData as any)?.themeHeaderOptions?.settingsHeaderOptions;
  const headerPosition: string | null = headerOpts?.headerPosition ?? null;
  const shrinkHeader: boolean = headerOpts?.shrinkHeader ?? false;
  const rawBp = headerOpts?.navbarBreakpoint;
  const navbarBreakpoint: string = (Array.isArray(rawBp) ? rawBp[0] : rawBp) ?? 'lg';
  const removeContentContainers = (cssData as any)?.themeGeneralOptions?.settingsThemeGeneralOptions?.removeContentContainers === true;

  const bodyClasses = [
    headerPosition ? `${headerPosition}-header-enabled` : 'static-header-enabled',
    shrinkHeader ? 'shrink-header-enabled' : null,
    customBackgroundCss ? 'custom-background' : null,
    removeContentContainers !== true ? 'include-content-containers' : null,
    `navbar-bp-${navbarBreakpoint}`,
    'include-header-containers',
    'include-footer-containers',
    'max-width-content-container',
    'max-width-footer-container',
  ].filter(Boolean).join(' ');

  return (
      <html lang="en">
        <head>
          {typekitId && (
            <>
              <link rel="preconnect" href="https://use.typekit.net" crossOrigin="anonymous" />
              <link rel="preconnect" href="https://p.typekit.net" crossOrigin="anonymous" />
            </>
          )}
          {globalCss && (
            <style dangerouslySetInnerHTML={{ __html: globalCss }} />
          )}
        </head>
        <body className={bodyClasses} data-bs-spy="scroll" data-bs-target="#primaryNavigation">
          {spritemapSvg && (
            <div aria-hidden="true" style={{ display: 'none' }} dangerouslySetInnerHTML={{ __html: spritemapSvg }} />
          )}
          {children}
          {/* Adobe Fonts async — loads after page paint, no render-blocking.
              Fonts swap in with font-display:swap (set per-font in the Typekit dashboard). */}
          {typekitId && (
            <Script
              id="adobe-fonts"
              strategy="afterInteractive"
              dangerouslySetInnerHTML={{
                __html: `
                  (function(d) {
                    var tk = d.createElement('script'), s = d.scripts[0];
                    tk.src = 'https://use.typekit.net/${typekitId}.js';
                    tk.async = true;
                    tk.onload = function() { try { Typekit.load({ async: true }); } catch(e) {} };
                    s.parentNode.insertBefore(tk, s);
                  })(document);
                `,
              }}
            />
          )}
        </body>
      </html>
  );
}
