import type { Metadata } from "next";
import Script from 'next/script';
import { print } from 'graphql';
// import 'bootstrap/dist/css/bootstrap.min.css';
import '../scss/global.scss';
// Phosphor Icons — CSS-only package; loaded here so the bundler resolves font URLs
// from node_modules. Uncomment additional weights as needed.
import '@phosphor-icons/web/regular';
// import '@phosphor-icons/web/bold';
// import '@phosphor-icons/web/fill';
import { gql } from '@apollo/client';
import { fetchGraphQL } from '@/lib/wp/client';

// Font loading patterns:
//
// Google Fonts — use next/font/google (self-hosted, inlined, zero external request):
//   import { Inter } from 'next/font/google';
//   const inter = Inter({ subsets: ['latin'] });
//   <body className={inter.className}>
//
// Adobe Fonts (Typekit) — use the async JS embed (non-blocking):
//   Set NEXT_PUBLIC_TYPEKIT_ID=your_kit_id in .env.local
//   The Script below handles it — the preconnects in <head> open the connection early.
//
// Never use <link rel="stylesheet"> for web fonts in the <head> — it blocks first paint.
// Never use CSS @import url() for web fonts — it blocks rendering and is discovered late.

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: [
        {
            url: '/icon.ico',
            media: '(prefers-color-scheme: light)',
        },
        {
            url: '/icon.ico',
            media: '(prefers-color-scheme: dark)',
        },
    ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const typekitId = process.env.NEXT_PUBLIC_TYPEKIT_ID;

  const GET_GLOBAL_CSS = gql`
    query GetGlobalCss {
      customizerCss
      fontOptionsCss
      globalStylesCss
      customizerSettings { customCss }
      themeHeaderOptions {
        settingsHeaderOptions {
          headerPosition
          shrinkHeader
        }
      }
    }
  `;

  const { data: cssData } = await fetchGraphQL<{
    customizerCss: string | null;
    fontOptionsCss: string | null;
    globalStylesCss: string | null;
    customizerSettings: { customCss: string | null } | null;
    themeHeaderOptions: { settingsHeaderOptions: { headerPosition: string | null; shrinkHeader: boolean | null } | null } | null;
  }>(print(GET_GLOBAL_CSS)).catch(() => ({ data: null })) as any;

  const globalCss = [
    cssData?.globalStylesCss,
    cssData?.customizerCss,
    cssData?.fontOptionsCss,
    cssData?.customizerSettings?.customCss,
  ].filter(Boolean).join('\n') || null;

  const headerOpts = (cssData as any)?.themeHeaderOptions?.settingsHeaderOptions;
  const headerPosition: string | null = headerOpts?.headerPosition ?? null;
  const shrinkHeader: boolean = headerOpts?.shrinkHeader ?? false;
  const bodyClasses = [
    headerPosition ? `${headerPosition}-header-enabled` : 'static-header-enabled',
    shrinkHeader ? 'shrink-header-enabled' : null,
  ].filter(Boolean).join(' ');

  return (
      <html lang="en">
        <head>
          {typekitId && (
            <>
              <link rel="preconnect" href="https://use.typekit.net" crossOrigin="anonymous" />
              <link rel="preconnect" href="https://p.typekit.net" crossOrigin="anonymous" />
            </>
          )}
          {globalCss && (
            <style dangerouslySetInnerHTML={{ __html: globalCss }} />
          )}
        </head>
        <body className={bodyClasses}>
          {children}
          {/* Adobe Fonts async — loads after page paint, no render-blocking.
              Fonts swap in with font-display:swap (set per-font in the Typekit dashboard). */}
          {typekitId && (
            <Script
              id="adobe-fonts"
              strategy="afterInteractive"
              dangerouslySetInnerHTML={{
                __html: `
                  (function(d) {
                    var tk = d.createElement('script'), s = d.scripts[0];
                    tk.src = 'https://use.typekit.net/${typekitId}.js';
                    tk.async = true;
                    tk.onload = function() { try { Typekit.load({ async: true }); } catch(e) {} };
                    s.parentNode.insertBefore(tk, s);
                  })(document);
                `,
              }}
            />
          )}
        </body>
      </html>
  );
}
