import {gql} from "@apollo/client";

export const GET_THEME_SETTINGS = gql`
    query GetThemeSettings {
      themeOptions {
        globalOptions {
          fontSizeLg
          fontSizeSm
          h1FontSize
          h2FontSize
          h3FontSize
          h4FontSize
          h5FontSize
          h6FontSize
          headingLineHeight
          linkDecorationLine
          linkDecorationStyle
          linkHoverDecorationLine
          linkHoverDecorationStyle
          paragraphFontSize
          paragraphLineHeight
          transitionDuration
          transitionProperties
          transitionTimingFunction
        }
        colorOptions {
          alertBgColor
          alertLinkColor
          alertLinkDecorationColor
          alertLinkDecorationHoverColor
          alertLinkHoverColor
          alertTextColor
          alertTextShadowColor
          bgColor
          buttonBorderBottomColor
          buttonBorderBottomHoverColor
          buttonBorderLeftColor
          buttonBorderLeftHoverColor
          buttonBorderRightColor
          buttonBorderRightHoverColor
          buttonBorderTopColor
          buttonBorderTopHoverColor
          buttonBoxShadowColor
          buttonBoxShadowHoverColor
          buttonColor
          buttonHoverColor
          buttonTextColor
          buttonTextHoverColor
          buttonTextShadowColor
          buttonTextShadowHoverColor
          cardBgColor
          cardBgHoverColor
          cardBorderColor
          cardBorderHoverColor
          cardLabelColor
          cardLabelHoverColor
          cardSubtitleColor
          cardSubtitleHoverColor
          cardTextColor
          cardTextHoverColor
          cardTitleColor
          cardTitleHoverColor
          dangerColor
          darkColor
          denaryColor
          footerAttributionBorderBottomColor
          footerAttributionBorderLeftColor
          footerAttributionBorderRightColor
          footerAttributionBorderTopColor
          footerAttributionColor
          footerBgColor
          footerBorderBottomColor
          footerBorderLeftColor
          footerBorderRightColor
          footerBorderTopColor
          footerBoxShadowColor
          footerBrandingColor
          footerBrandingHoverColor
          footerContactInfoColor
          footerContactInfoLinkColor
          footerContactInfoLinkHoverColor
          footerCopyrightColor
          footerCtaBorderBottomColor
          footerCtaBorderBottomHoverColor
          footerCtaBorderLeftColor
          footerCtaBorderLeftHoverColor
          footerCtaBorderRightColor
          footerCtaBorderRightHoverColor
          footerCtaBorderTopColor
          footerCtaBorderTopHoverColor
          footerCtaColor
          footerCtaHoverColor
          footerCtaTextColor
          footerCtaTextHoverColor
          footerDisclaimerColor
          footerLinkColor
          footerLinkHoverColor
          footerNavLinkColor
          footerNavLinkDecorationColor
          footerNavLinkDecorationHoverColor
          footerNavLinkHoverColor
          footerSearchButtonBorderBottomColor
          footerSearchButtonBorderBottomHoverColor
          footerSearchButtonBorderLeftColor
          footerSearchButtonBorderLeftHoverColor
          footerSearchButtonBorderRightColor
          footerSearchButtonBorderRightHoverColor
          footerSearchButtonBorderTopColor
          footerSearchButtonBorderTopHoverColor
          footerSearchButtonColor
          footerSearchButtonHoverColor
          footerSearchButtonTextColor
          footerSearchButtonTextHoverColor
          footerSearchInputBackgroundColor
          footerSearchInputBackgroundHoverColor
          footerSearchInputBorderColor
          footerSearchInputBorderHoverColor
          footerSocialNavBgColor
          footerSocialNavItemBgColor
          footerSocialNavItemBgHoverColor
          footerSocialNavItemBorderColor
          footerSocialNavItemBorderHoverColor
          footerSocialNavItemColor
          footerSocialNavItemHoverColor
          footerTextColor
          headerBgColor
          headerBorderBottomColor
          headerBorderLeftColor
          headerBorderRightColor
          headerBorderTopColor
          headerBoxShadowColor
          headerBrandingColor
          headerBrandingHoverColor
          headerCtaBorderBottomColor
          headerCtaBorderBottomHoverColor
          headerCtaBorderLeftColor
          headerCtaBorderLeftHoverColor
          headerCtaBorderRightColor
          headerCtaBorderRightHoverColor
          headerCtaBorderTopColor
          headerCtaBorderTopHoverColor
          headerCtaColor
          headerCtaHoverColor
          headerCtaTextColor
          headerCtaTextHoverColor
          headerLinkColor
          headerLinkHoverColor
          headerMobileCtaBorderBottomColor
          headerMobileCtaBorderBottomHoverColor
          headerMobileCtaBorderLeftColor
          headerMobileCtaBorderLeftHoverColor
          headerMobileCtaBorderRightColor
          headerMobileCtaBorderRightHoverColor
          headerMobileCtaBorderTopColor
          headerMobileCtaBorderTopHoverColor
          headerMobileCtaColor
          headerMobileCtaHoverColor
          headerMobileCtaTextColor
          headerMobileCtaTextHoverColor
          headerSearchButtonBorderBottomColor
          headerSearchButtonBorderBottomHoverColor
          headerSearchButtonBorderLeftColor
          headerSearchButtonBorderLeftHoverColor
          headerSearchButtonBorderRightColor
          headerSearchButtonBorderRightHoverColor
          headerSearchButtonBorderTopColor
          headerSearchButtonBorderTopHoverColor
          headerSearchButtonColor
          headerSearchButtonHoverColor
          headerSearchButtonTextColor
          headerSearchButtonTextHoverColor
          headerSearchInputBackgroundColor
          headerSearchInputBackgroundHoverColor
          headerSearchInputBorderColor
          headerSearchInputBorderHoverColor
          headerSocialNavBgColor
          headerSocialNavItemBgColor
          headerSocialNavItemBgHoverColor
          headerSocialNavItemBorderColor
          headerSocialNavItemBorderHoverColor
          headerSocialNavItemColor
          headerSocialNavItemHoverColor
          headerTextColor
          infoColor
          inputBackgroundColor
          inputBackgroundHoverColor
          inputBorderColor
          inputBorderHoverColor
          lightColor
          linkColor
          linkDecorationColor
          linkHoverColor
          linkHoverDecorationColor
          modalBgColor
          modalBorderColor
          modalOverlayColor
          modalTextColor
          modalTitleColor
          navBgColor
          navBgMobileColor
          navBorderBottomColor
          navBorderLeftColor
          navBorderRightColor
          navBorderTopColor
          navMobileBorderBottomColor
          navMobileBorderLeftColor
          navMobileBorderRightColor
          navMobileBorderTopColor
          navToggleActiveColor
          navToggleColor
          nonaryColor
          octonaryColor
          primaryColor
          primaryNavLinkColor
          primaryNavLinkDecorationColor
          primaryNavLinkDecorationHoverColor
          primaryNavLinkHoverColor
          quarternaryColor
          quinaryColor
          secondaryColor
          secondaryNavLinkColor
          secondaryNavLinkDecorationColor
          secondaryNavLinkDecorationHoverColor
          secondaryNavLinkHoverColor
          senaryColor
          septenaryColor
          socialNavBgColor
          socialNavItemBgColor
          socialNavItemBgHoverColor
          socialNavItemBorderColor
          socialNavItemBorderHoverColor
          socialNavItemColor
          socialNavItemHoverColor
          successColor
          tertiaryColor
          textColor
          utilityNavLinkColor
          utilityNavLinkDecorationColor
          utilityNavLinkDecorationHoverColor
          utilityNavLinkHoverColor
          warningColor
        }
        alertOptions {
          alertFontSize
          alertFontSizeMobile
          alertFontStyle
          alertFontWeight
          alertLetterSpacing
          alertLetterSpacingMobile
          alertLineHeight
          alertLineHeightMobile
          alertLinkDecorationLine
          alertLinkDecorationStyle
          alertLinkHoverDecorationLine
          alertLinkHoverDecorationStyle
          alertPaddingHorizontal
          alertPaddingVertical
          alertTextShadowBlur
          alertTextShadowX
          alertTextShadowY
          alertTextTransform
        }
        buttonOptions {
          buttonBorderBottomLeftRadius
          buttonBorderBottomLeftRadiusHover
          buttonBorderBottomRightRadius
          buttonBorderBottomRightRadiusHover
          buttonBorderBottomStyle
          buttonBorderBottomStyleHover
          buttonBorderBottomWidth
          buttonBorderBottomWidthHover
          buttonBorderLeftStyle
          buttonBorderLeftStyleHover
          buttonBorderLeftWidth
          buttonBorderLeftWidthHover
          buttonBorderRightStyle
          buttonBorderRightStyleHover
          buttonBorderRightWidth
          buttonBorderRightWidthHover
          buttonBorderTopLeftRadius
          buttonBorderTopLeftRadiusHover
          buttonBorderTopRightRadius
          buttonBorderTopRightRadiusHover
          buttonBorderTopStyle
          buttonBorderTopStyleHover
          buttonBorderTopWidth
          buttonBorderTopWidthHover
          buttonBoxShadowBlur
          buttonBoxShadowHoverBlur
          buttonBoxShadowHoverSpread
          buttonBoxShadowHoverX
          buttonBoxShadowHoverY
          buttonBoxShadowSpread
          buttonBoxShadowX
          buttonBoxShadowY
          buttonFontSize
          buttonFontSizeHover
          buttonFontStyle
          buttonFontStyleHover
          buttonFontWeight
          buttonFontWeightHover
          buttonHorizontalPadding
          buttonHorizontalPaddingHover
          buttonLetterSpacing
          buttonLetterSpacingHover
          buttonLineHeight
          buttonLineHeightHover
          buttonTextShadowBlur
          buttonTextShadowHoverBlur
          buttonTextShadowHoverX
          buttonTextShadowHoverY
          buttonTextShadowX
          buttonTextShadowY
          buttonTextTransform
          buttonTextTransformHover
          buttonVerticalPadding
          buttonVerticalPaddingHover
        }
        cardOptions {
          cardBorderRadius
          cardBorderStyle
          cardBorderWidth
          cardLabelFontSize
          cardLabelFontStyle
          cardLabelFontWeight
          cardLabelLineHeight
          cardSubtitleFontSize
          cardSubtitleFontStyle
          cardSubtitleFontWeight
          cardSubtitleLineHeight
          cardTextAlign
          cardTextFontSize
          cardTextFontStyle
          cardTextFontWeight
          cardTextLineHeight
          cardTitleFontSize
          cardTitleFontStyle
          cardTitleFontWeight
          cardTitleLineHeight
        }
        formOptions {
          inputBorderRadius
          inputBorderStyle
          inputBorderWidth
          inputFontSize
          inputHorizontalPadding
          inputHoverHorizontalPadding
          inputLineHeight
          inputVerticalPadding
        }
        modalOptions {
          modalBorderRadius
          modalBorderStyle
          modalBorderWidth
          modalTextAlign
          modalTextFontSize
          modalTextFontStyle
          modalTextFontWeight
          modalTextLetterSpacing
          modalTextLineHeight
          modalTitleFontSize
          modalTitleFontStyle
          modalTitleFontWeight
          modalTitleLetterSpacing
          modalTitleLineHeight
          modalTitleTextTransform
          numberModalWidth
          rangeModalWidth
          unitSelectorModalWidth
        }
        headerOptions {
          headerPaddingTop
          headerPaddingBottom
          headerPaddingLeft
          headerPaddingRight
          headerMobilePaddingTop
          headerMobilePaddingBottom
          headerMobilePaddingLeft
          headerMobilePaddingRight
          headerBorderTopWidth
          headerBorderBottomWidth
          headerBorderLeftWidth
          headerBorderRightWidth
          headerBorderTopStyle
          headerBorderRightStyle
          headerBorderBottomStyle
          headerBorderLeftStyle
          headerBorderTopLeftRadius
          headerBorderTopRightRadius
          headerBorderBottomLeftRadius
          headerBorderBottomRightRadius
          headerBoxShadowX
          headerBoxShadowY
          headerBoxShadowBlur
          headerBoxShadowSpread
        }
        headerLayoutOptions {
          alignMobileCtaButton
          alignNavToContent
          centerHeaderContent
          centerMobileNavContent
          centerNavToggle
          desktopLogoRight
          fullHeightMobileCtaButton
          fullScreenNav
          fullWidthHeader
          hideHeaderCta
          hideHeaderSearch
          hidePrimaryNav
          hideSecondaryNav
          hideSocialNav
          inlineMobileNavToggle
          mobileNavMenuPosition
          navToggleRelativeToContainer
          reverseMobileButtons
          showMobileCtaButton
        }
        headerBrandingOptions {
          headerBrandingFontSize
          headerBrandingFontSizeMobile
          headerBrandingFontStyle
          headerBrandingFontWeight
          headerBrandingLetterSpacing
          headerBrandingLetterSpacingMobile
          headerBrandingLineHeight
          headerBrandingLineHeightMobile
          headerBrandingMarginBottom
          headerBrandingMarginLeft
          headerBrandingMarginRight
          headerBrandingMarginTop
          headerBrandingMobileMarginBottom
          headerBrandingMobileMarginLeft
          headerBrandingMobileMarginRight
          headerBrandingMobileMarginTop
          headerBrandingTextShadowBlur
          headerBrandingTextShadowX
          headerBrandingTextShadowY
          headerBrandingTextTransform
          headerBrandingWidth
          headerSloganFontSize
          headerSloganFontSizeMobile
          headerSloganFontStyle
          headerSloganFontWeight
          headerSloganLetterSpacing
          headerSloganLetterSpacingMobile
          headerSloganLineHeight
          headerSloganLineHeightMobile
          headerSloganTextShadowX
          headerSloganTextShadowY
          headerSloganTextTransform
        }
        headerCtaOptions {
          headerCtaBorderBottomLeftRadius
          headerCtaBorderBottomLeftRadiusHover
          headerCtaBorderBottomRightRadius
          headerCtaBorderBottomRightRadiusHover
          headerCtaBorderBottomStyle
          headerCtaBorderBottomStyleHover
          headerCtaBorderBottomWidth
          headerCtaBorderBottomWidthHover
          headerCtaBorderLeftStyle
          headerCtaBorderLeftStyleHover
          headerCtaBorderLeftWidth
          headerCtaBorderLeftWidthHover
          headerCtaBorderRightStyle
          headerCtaBorderRightStyleHover
          headerCtaBorderRightWidth
          headerCtaBorderRightWidthHover
          headerCtaBorderTopLeftRadius
          headerCtaBorderTopLeftRadiusHover
          headerCtaBorderTopRightRadius
          headerCtaBorderTopRightRadiusHover
          headerCtaBorderTopStyle
          headerCtaBorderTopStyleHover
          headerCtaBorderTopWidth
          headerCtaBorderTopWidthHover
          headerCtaBoxShadowBlur
          headerCtaBoxShadowHoverBlur
          headerCtaBoxShadowHoverSpread
          headerCtaBoxShadowHoverX
          headerCtaBoxShadowHoverY
          headerCtaBoxShadowSpread
          headerCtaBoxShadowX
          headerCtaBoxShadowY
          headerCtaFontSize
          headerCtaFontSizeHover
          headerCtaFontStyle
          headerCtaFontStyleHover
          headerCtaFontWeight
          headerCtaFontWeightHover
          headerCtaHorizontalPadding
          headerCtaHorizontalPaddingHover
          headerCtaLetterSpacing
          headerCtaLetterSpacingHover
          headerCtaLineHeight
          headerCtaLineHeightHover
          headerCtaTextShadowBlur
          headerCtaTextShadowHoverBlur
          headerCtaTextShadowHoverX
          headerCtaTextShadowHoverY
          headerCtaTextShadowX
          headerCtaTextShadowY
          headerCtaTextTransform
          headerCtaTextTransformHover
          headerCtaVerticalPadding
          headerCtaVerticalPaddingHover
        }
        headerCtaMobileOptions {
          headerCtaMobileBorderBottomLeftRadius
          headerCtaMobileBorderBottomLeftRadiusHover
          headerCtaMobileBorderBottomRightRadius
          headerCtaMobileBorderBottomRightRadiusHover
          headerCtaMobileBorderBottomStyle
          headerCtaMobileBorderBottomStyleHover
          headerCtaMobileBorderBottomWidth
          headerCtaMobileBorderBottomWidthHover
          headerCtaMobileBorderLeftStyle
          headerCtaMobileBorderLeftStyleHover
          headerCtaMobileBorderLeftWidth
          headerCtaMobileBorderLeftWidthHover
          headerCtaMobileBorderRightStyle
          headerCtaMobileBorderRightStyleHover
          headerCtaMobileBorderRightWidth
          headerCtaMobileBorderRightWidthHover
          headerCtaMobileBorderTopLeftRadius
          headerCtaMobileBorderTopLeftRadiusHover
          headerCtaMobileBorderTopRightRadius
          headerCtaMobileBorderTopRightRadiusHover
          headerCtaMobileBorderTopStyle
          headerCtaMobileBorderTopStyleHover
          headerCtaMobileBorderTopWidth
          headerCtaMobileBorderTopWidthHover
          headerCtaMobileBoxShadowBlur
          headerCtaMobileBoxShadowHoverBlur
          headerCtaMobileBoxShadowHoverSpread
          headerCtaMobileBoxShadowHoverX
          headerCtaMobileBoxShadowHoverY
          headerCtaMobileBoxShadowSpread
          headerCtaMobileBoxShadowX
          headerCtaMobileBoxShadowY
          headerCtaMobileFontSize
          headerCtaMobileFontSizeHover
          headerCtaMobileFontStyle
          headerCtaMobileFontStyleHover
          headerCtaMobileFontWeight
          headerCtaMobileFontWeightHover
          headerCtaMobileHorizontalPadding
          headerCtaMobileHorizontalPaddingHover
          headerCtaMobileLetterSpacing
          headerCtaMobileLetterSpacingHover
          headerCtaMobileLineHeight
          headerCtaMobileLineHeightHover
          headerCtaMobileTextShadowBlur
          headerCtaMobileTextShadowHoverBlur
          headerCtaMobileTextShadowHoverX
          headerCtaMobileTextShadowHoverY
          headerCtaMobileTextShadowX
          headerCtaMobileTextShadowY
          headerCtaMobileTextTransform
          headerCtaMobileTextTransformHover
          headerCtaMobileVerticalPadding
          headerCtaMobileVerticalPaddingHover
        }
        headerSearchOptions {
          headerSearchInputBorderRadius
          headerSearchInputBorderStyle
          headerSearchInputBorderWidth
          headerSearchInputFontSize
          headerSearchInputFontStyle
          headerSearchInputFontWeight
          headerSearchInputHorizontalPadding
          headerSearchInputHoverHorizontalPadding
          headerSearchInputLetterSpacing
          headerSearchInputLineHeight
          headerSearchInputTextTransform
          headerSearchInputVerticalPadding
          headerSearchSubmitBorderBottomLeftRadius
          headerSearchSubmitBorderBottomLeftRadiusHover
          headerSearchSubmitBorderBottomRightRadius
          headerSearchSubmitBorderBottomRightRadiusHover
          headerSearchSubmitBorderBottomStyle
          headerSearchSubmitBorderBottomStyleHover
          headerSearchSubmitBorderBottomWidth
          headerSearchSubmitBorderBottomWidthHover
          headerSearchSubmitBorderLeftStyle
          headerSearchSubmitBorderLeftStyleHover
          headerSearchSubmitBorderLeftWidth
          headerSearchSubmitBorderLeftWidthHover
          headerSearchSubmitBorderRightStyle
          headerSearchSubmitBorderRightStyleHover
          headerSearchSubmitBorderRightWidth
          headerSearchSubmitBorderRightWidthHover
          headerSearchSubmitBorderTopLeftRadius
          headerSearchSubmitBorderTopLeftRadiusHover
          headerSearchSubmitBorderTopRightRadius
          headerSearchSubmitBorderTopRightRadiusHover
          headerSearchSubmitBorderTopStyle
          headerSearchSubmitBorderTopStyleHover
          headerSearchSubmitBorderTopWidth
          headerSearchSubmitBorderTopWidthHover
          headerSearchSubmitBoxShadowBlur
          headerSearchSubmitBoxShadowHoverBlur
          headerSearchSubmitBoxShadowHoverSpread
          headerSearchSubmitBoxShadowHoverX
          headerSearchSubmitBoxShadowHoverY
          headerSearchSubmitBoxShadowSpread
          headerSearchSubmitBoxShadowX
          headerSearchSubmitBoxShadowY
          headerSearchSubmitFontSize
          headerSearchSubmitFontSizeHover
          headerSearchSubmitFontStyle
          headerSearchSubmitFontStyleHover
          headerSearchSubmitFontWeight
          headerSearchSubmitFontWeightHover
          headerSearchSubmitHorizontalPadding
          headerSearchSubmitHorizontalPaddingHover
          headerSearchSubmitLetterSpacing
          headerSearchSubmitLetterSpacingHover
          headerSearchSubmitLineHeight
          headerSearchSubmitLineHeightHover
          headerSearchSubmitTextShadowBlur
          headerSearchSubmitTextShadowHoverBlur
          headerSearchSubmitTextShadowHoverX
          headerSearchSubmitTextShadowHoverY
          headerSearchSubmitTextShadowX
          headerSearchSubmitTextShadowY
          headerSearchSubmitTextTransform
          headerSearchSubmitTextTransformHover
          headerSearchSubmitVerticalPadding
          headerSearchSubmitVerticalPaddingHover
        }
        headerSocialNavOptions {
          headerSocialNavFlexAlign
          headerSocialNavIconHeight
          headerSocialNavIconWidth
          headerSocialNavItemBorderRadius
          headerSocialNavItemBorderStyle
          headerSocialNavItemBorderWidth
          headerSocialNavItemHeight
          headerSocialNavItemHoverBorderRadius
          headerSocialNavItemHoverBorderStyle
          headerSocialNavItemHoverBorderWidth
          headerSocialNavItemSpacing
          headerSocialNavItemWidth
          headerSocialNavMarginBottom
          headerSocialNavMarginTop
          headerSocialNavPaddingBottom
          headerSocialNavPaddingLeft
          headerSocialNavPaddingRight
          headerSocialNavPaddingTop
          headerSocialNavTextAlign
        }
        navbarOptions {
          mobileNavFlexAlign
          mobileNavTextAlign
          navbarBorderBottomLeftRadius
          navbarBorderBottomRightRadius
          navbarBorderBottomStyle
          navbarBorderBottomWidth
          navbarBorderLeftStyle
          navbarBorderLeftWidth
          navbarBorderRightStyle
          navbarBorderRightWidth
          navbarBorderTopLeftRadius
          navbarBorderTopRightRadius
          navbarBorderTopStyle
          navbarBorderTopWidth
          navbarMobileBorderBottomLeftRadius
          navbarMobileBorderBottomRightRadius
          navbarMobileBorderBottomStyle
          navbarMobileBorderBottomWidth
          navbarMobileBorderLeftStyle
          navbarMobileBorderLeftWidth
          navbarMobileBorderRightStyle
          navbarMobileBorderRightWidth
          navbarMobileBorderTopLeftRadius
          navbarMobileBorderTopRightRadius
          navbarMobileBorderTopStyle
          navbarMobileBorderTopWidth
          navbarPaddingBottom
          navbarPaddingLeft
          navbarPaddingRight
          navbarPaddingTop
          navbarToggleHorizontalPadding
          navbarToggleHorizontalPosition
          navbarToggleHoverOpacity
          navbarToggleLayerBorderRadius
          navbarToggleLayerHeight
          navbarToggleLayerSpacing
          navbarToggleLayerWidth
          navbarToggleMarginBottom
          navbarToggleMarginLeft
          navbarToggleMarginRight
          navbarToggleMarginTop
          navbarToggleVerticalPadding
          navbarToggleVerticalPosition
          numberMobileNavHeight
          numberMobileNavWidth
          rangeMobileNavHeight
          rangeMobileNavWidth
          unitSelectorMobileNavHeight
          unitSelectorMobileNavWidth
        }
        primaryNavOptions {
          primaryNavFontSize
          primaryNavFontStyle
          primaryNavFontWeight
          primaryNavHorizontalPadding
          primaryNavItemHorizontalPadding
          primaryNavItemMobileHorizontalPadding
          primaryNavItemMobileVerticalPadding
          primaryNavItemVerticalPadding
          primaryNavLetterSpacing
          primaryNavLineHeight
          primaryNavLinkDecorationLine
          primaryNavLinkDecorationStyle
          primaryNavLinkHoverDecorationLine
          primaryNavLinkHoverDecorationStyle
          primaryNavMobileFontSize
          primaryNavMobileLetterSpacing
          primaryNavMobileLineHeight
          primaryNavTextTransform
          primaryNavVerticalPadding
        }
        secondaryNavOptions {
          secondaryNavFontSize
          secondaryNavFontStyle
          secondaryNavFontWeight
          secondaryNavHorizontalPadding
          secondaryNavItemHorizontalPadding
          secondaryNavItemMobileHorizontalPadding
          secondaryNavItemMobileVerticalPadding
          secondaryNavItemVerticalPadding
          secondaryNavLetterSpacing
          secondaryNavLineHeight
          secondaryNavLinkDecorationLine
          secondaryNavLinkDecorationStyle
          secondaryNavLinkHoverDecorationLine
          secondaryNavLinkHoverDecorationStyle
          secondaryNavMobileFontSize
          secondaryNavMobileLetterSpacing
          secondaryNavMobileLineHeight
          secondaryNavTextTransform
          secondaryNavVerticalPadding
        }
        utilityNavOptions {
          utilityNavFontSize
          utilityNavFontStyle
          utilityNavFontWeight
          utilityNavHorizontalPadding
          utilityNavItemHorizontalPadding
          utilityNavItemMobileHorizontalPadding
          utilityNavItemMobileVerticalPadding
          utilityNavItemVerticalPadding
          utilityNavLetterSpacing
          utilityNavLineHeight
          utilityNavLinkDecorationLine
          utilityNavLinkDecorationStyle
          utilityNavLinkHoverDecorationLine
          utilityNavLinkHoverDecorationStyle
          utilityNavMobileFontSize
          utilityNavMobileLetterSpacing
          utilityNavMobileLineHeight
          utilityNavTextTransform
          utilityNavVerticalPadding
        }
        socialNavOptions {
          socialNavFlexAlign
          socialNavIconHeight
          socialNavIconWidth
          socialNavItemBorderRadius
          socialNavItemBorderStyle
          socialNavItemBorderWidth
          socialNavItemHeight
          socialNavItemHoverBorderRadius
          socialNavItemHoverBorderStyle
          socialNavItemHoverBorderWidth
          socialNavItemSpacing
          socialNavItemWidth
          socialNavMarginBottom
          socialNavMarginTop
          socialNavPaddingBottom
          socialNavPaddingLeft
          socialNavPaddingRight
          socialNavPaddingTop
          socialNavTextAlign
        }
        footerOptions {
          footerTextAlign
          footerFlexAlign
          footerPaddingTop
          footerPaddingBottom
          footerPaddingLeft
          footerPaddingRight
          footerMobilePaddingTop
          footerMobilePaddingBottom
          footerMobilePaddingLeft
          footerMobilePaddingRight
          footerBorderTopWidth
          footerBorderBottomWidth
          footerBorderLeftWidth
          footerBorderRightWidth
          footerBorderTopStyle
          footerBorderRightStyle
          footerBorderBottomStyle
          footerBorderLeftStyle
          footerBorderTopLeftRadius
          footerBorderTopRightRadius
          footerBorderBottomLeftRadius
          footerBorderBottomRightRadius
          footerBoxShadowX
          footerBoxShadowY
          footerBoxShadowBlur
          footerBoxShadowSpread
        }
        footerLayoutOptions {
          footerReverseColumnLayout
          footerReverseMetaColumns
          footerTwoColumnLayout
          hideFooterAttribution
          hideFooterBrand
          hideFooterContactInfo
          hideFooterCopyright
          hideFooterCopyrightIcon
          hideFooterCopyrightLabel
          hideFooterCopyrightSiteName
          hideFooterCopyrightYear
          hideFooterCta
          hideFooterDisclaimer
          hideFooterNav
          hideFooterSearch
          hideFooterSocialNav
          hideFooterUtilityNav
        }
        footerBrandingOptions {
          footerBrandingFontSize
          footerBrandingFontSizeMobile
          footerBrandingFontStyle
          footerBrandingFontWeight
          footerBrandingLetterSpacing
          footerBrandingLetterSpacingMobile
          footerBrandingLineHeight
          footerBrandingLineHeightMobile
          footerBrandingMarginBottom
          footerBrandingMarginLeft
          footerBrandingMarginRight
          footerBrandingMarginTop
          footerBrandingMobileMarginBottom
          footerBrandingMobileMarginLeft
          footerBrandingMobileMarginRight
          footerBrandingMobileMarginTop
          footerBrandingTextShadowBlur
          footerBrandingTextShadowX
          footerBrandingTextShadowY
          footerBrandingTextTransform
          footerBrandingWidth
          footerSloganFontSize
          footerSloganFontSizeMobile
          footerSloganFontStyle
          footerSloganFontWeight
          footerSloganLetterSpacing
          footerSloganLetterSpacingMobile
          footerSloganLineHeight
          footerSloganLineHeightMobile
          footerSloganTextShadowX
          footerSloganTextShadowY
          footerSloganTextTransform
        }
        footerNavOptions {
          footerNavFontSize
          footerNavFontStyle
          footerNavFontWeight
          footerNavHorizontalPadding
          footerNavItemHorizontalPadding
          footerNavItemMobileHorizontalPadding
          footerNavItemMobileVerticalPadding
          footerNavItemVerticalPadding
          footerNavLetterSpacing
          footerNavLineHeight
          footerNavLinkDecorationLine
          footerNavLinkDecorationStyle
          footerNavLinkHoverDecorationLine
          footerNavLinkHoverDecorationStyle
          footerNavMobileFontSize
          footerNavMobileLetterSpacing
          footerNavMobileLineHeight
          footerNavTextTransform
          footerNavVerticalPadding
        }
        footerCtaOptions {
          footerCtaBorderBottomLeftRadius
          footerCtaBorderBottomLeftRadiusHover
          footerCtaBorderBottomRightRadius
          footerCtaBorderBottomRightRadiusHover
          footerCtaBorderBottomStyle
          footerCtaBorderBottomStyleHover
          footerCtaBorderBottomWidth
          footerCtaBorderBottomWidthHover
          footerCtaBorderLeftStyle
          footerCtaBorderLeftStyleHover
          footerCtaBorderLeftWidth
          footerCtaBorderLeftWidthHover
          footerCtaBorderRightStyle
          footerCtaBorderRightStyleHover
          footerCtaBorderRightWidth
          footerCtaBorderRightWidthHover
          footerCtaBorderTopLeftRadius
          footerCtaBorderTopLeftRadiusHover
          footerCtaBorderTopRightRadius
          footerCtaBorderTopRightRadiusHover
          footerCtaBorderTopStyle
          footerCtaBorderTopStyleHover
          footerCtaBorderTopWidth
          footerCtaBorderTopWidthHover
          footerCtaBoxShadowBlur
          footerCtaBoxShadowHoverBlur
          footerCtaBoxShadowHoverSpread
          footerCtaBoxShadowHoverX
          footerCtaBoxShadowHoverY
          footerCtaBoxShadowSpread
          footerCtaBoxShadowX
          footerCtaBoxShadowY
          footerCtaFontSize
          footerCtaFontSizeHover
          footerCtaFontStyle
          footerCtaFontStyleHover
          footerCtaFontWeight
          footerCtaFontWeightHover
          footerCtaHorizontalPadding
          footerCtaHorizontalPaddingHover
          footerCtaLetterSpacing
          footerCtaLetterSpacingHover
          footerCtaLineHeight
          footerCtaLineHeightHover
          footerCtaTextShadowBlur
          footerCtaTextShadowHoverBlur
          footerCtaTextShadowHoverX
          footerCtaTextShadowHoverY
          footerCtaTextShadowX
          footerCtaTextShadowY
          footerCtaTextTransform
          footerCtaTextTransformHover
          footerCtaVerticalPadding
          footerCtaVerticalPaddingHover
        }
        footerSearchOptions {
          footerSearchInputBorderRadius
          footerSearchInputBorderStyle
          footerSearchInputBorderWidth
          footerSearchInputFontSize
          footerSearchInputFontStyle
          footerSearchInputFontWeight
          footerSearchInputHorizontalPadding
          footerSearchInputHoverHorizontalPadding
          footerSearchInputLetterSpacing
          footerSearchInputLineHeight
          footerSearchInputTextTransform
          footerSearchInputVerticalPadding
          footerSearchSubmitBorderBottomLeftRadius
          footerSearchSubmitBorderBottomLeftRadiusHover
          footerSearchSubmitBorderBottomRightRadius
          footerSearchSubmitBorderBottomRightRadiusHover
          footerSearchSubmitBorderBottomStyle
          footerSearchSubmitBorderBottomStyleHover
          footerSearchSubmitBorderBottomWidth
          footerSearchSubmitBorderBottomWidthHover
          footerSearchSubmitBorderLeftStyle
          footerSearchSubmitBorderLeftStyleHover
          footerSearchSubmitBorderLeftWidth
          footerSearchSubmitBorderLeftWidthHover
          footerSearchSubmitBorderRightStyle
          footerSearchSubmitBorderRightStyleHover
          footerSearchSubmitBorderRightWidth
          footerSearchSubmitBorderRightWidthHover
          footerSearchSubmitBorderTopLeftRadius
          footerSearchSubmitBorderTopLeftRadiusHover
          footerSearchSubmitBorderTopRightRadius
          footerSearchSubmitBorderTopRightRadiusHover
          footerSearchSubmitBorderTopStyle
          footerSearchSubmitBorderTopStyleHover
          footerSearchSubmitBorderTopWidth
          footerSearchSubmitBorderTopWidthHover
          footerSearchSubmitBoxShadowBlur
          footerSearchSubmitBoxShadowHoverBlur
          footerSearchSubmitBoxShadowHoverSpread
          footerSearchSubmitBoxShadowHoverX
          footerSearchSubmitBoxShadowHoverY
          footerSearchSubmitBoxShadowSpread
          footerSearchSubmitBoxShadowX
          footerSearchSubmitBoxShadowY
          footerSearchSubmitFontSize
          footerSearchSubmitFontSizeHover
          footerSearchSubmitFontStyle
          footerSearchSubmitFontStyleHover
          footerSearchSubmitFontWeight
          footerSearchSubmitFontWeightHover
          footerSearchSubmitHorizontalPadding
          footerSearchSubmitHorizontalPaddingHover
          footerSearchSubmitLetterSpacing
          footerSearchSubmitLetterSpacingHover
          footerSearchSubmitLineHeight
          footerSearchSubmitLineHeightHover
          footerSearchSubmitTextShadowBlur
          footerSearchSubmitTextShadowHoverBlur
          footerSearchSubmitTextShadowHoverX
          footerSearchSubmitTextShadowHoverY
          footerSearchSubmitTextShadowX
          footerSearchSubmitTextShadowY
          footerSearchSubmitTextTransform
          footerSearchSubmitTextTransformHover
          footerSearchSubmitVerticalPadding
          footerSearchSubmitVerticalPaddingHover
        }
        footerSocialNavOptions {
          footerSocialNavFlexAlign
          footerSocialNavIconHeight
          footerSocialNavIconWidth
          footerSocialNavItemBorderRadius
          footerSocialNavItemBorderStyle
          footerSocialNavItemBorderWidth
          footerSocialNavItemHeight
          footerSocialNavItemHoverBorderRadius
          footerSocialNavItemHoverBorderStyle
          footerSocialNavItemHoverBorderWidth
          footerSocialNavItemSpacing
          footerSocialNavItemWidth
          footerSocialNavMarginBottom
          footerSocialNavMarginTop
          footerSocialNavPaddingBottom
          footerSocialNavPaddingLeft
          footerSocialNavPaddingRight
          footerSocialNavPaddingTop
          footerSocialNavTextAlign
        }
        footerContactInfoOptions {
          footerContactInfoItemFontSize
          footerContactInfoItemFontSizeMobile
          footerContactInfoItemFontStyle
          footerContactInfoItemFontWeight
          footerContactInfoItemHorizontalPadding
          footerContactInfoItemLabelFontSize
          footerContactInfoItemLabelFontSizeMobile
          footerContactInfoItemLabelFontStyle
          footerContactInfoItemLabelFontWeight
          footerContactInfoItemLabelLetterSpacing
          footerContactInfoItemLabelLetterSpacingMobile
          footerContactInfoItemLabelLineHeight
          footerContactInfoItemLabelLineHeightMobile
          footerContactInfoItemLabelTextTransform
          footerContactInfoItemLetterSpacing
          footerContactInfoItemLetterSpacingMobile
          footerContactInfoItemLineHeight
          footerContactInfoItemLineHeightMobile
          footerContactInfoItemMarginBottom
          footerContactInfoItemMarginLeft
          footerContactInfoItemMarginRight
          footerContactInfoItemMarginTop
          footerContactInfoItemMobileHorizontalPadding
          footerContactInfoItemMobileMarginBottom
          footerContactInfoItemMobileMarginLeft
          footerContactInfoItemMobileMarginRight
          footerContactInfoItemMobileMarginTop
          footerContactInfoItemMobileVerticalPadding
          footerContactInfoItemTextTransform
          footerContactInfoItemVerticalPadding
          footerContactInfoMarginBottom
          footerContactInfoMarginLeft
          footerContactInfoMarginRight
          footerContactInfoMarginTop
          footerContactInfoMobileMarginBottom
          footerContactInfoMobileMarginLeft
          footerContactInfoMobileMarginRight
          footerContactInfoMobileMarginTop
        }
        footerCopyrightOptions {
          footerCopyrightFontSize
          footerCopyrightFontSizeMobile
          footerCopyrightFontStyle
          footerCopyrightFontWeight
          footerCopyrightHorizontalPadding
          footerCopyrightLetterSpacing
          footerCopyrightLetterSpacingMobile
          footerCopyrightLineHeight
          footerCopyrightLineHeightMobile
          footerCopyrightMarginBottom
          footerCopyrightMarginLeft
          footerCopyrightMarginRight
          footerCopyrightMarginTop
          footerCopyrightMobileHorizontalPadding
          footerCopyrightMobileMarginBottom
          footerCopyrightMobileMarginLeft
          footerCopyrightMobileMarginRight
          footerCopyrightMobileMarginTop
          footerCopyrightMobileVerticalPadding
          footerCopyrightTextTransform
          footerCopyrightVerticalPadding
        }
        footerDisclaimerOptions {
          footerDisclaimerFontSize
          footerDisclaimerFontSizeMobile
          footerDisclaimerFontStyle
          footerDisclaimerFontWeight
          footerDisclaimerHorizontalPadding
          footerDisclaimerLetterSpacing
          footerDisclaimerLetterSpacingMobile
          footerDisclaimerLineHeight
          footerDisclaimerLineHeightMobile
          footerDisclaimerMarginBottom
          footerDisclaimerMarginLeft
          footerDisclaimerMarginRight
          footerDisclaimerMarginTop
          footerDisclaimerMobileHorizontalPadding
          footerDisclaimerMobileMarginBottom
          footerDisclaimerMobileMarginLeft
          footerDisclaimerMobileMarginRight
          footerDisclaimerMobileMarginTop
          footerDisclaimerMobileVerticalPadding
          footerDisclaimerTextTransform
          footerDisclaimerVerticalPadding
          numberFooterDisclaimerWidth
          rangeFooterDisclaimerWidth
          unitSelectorFooterDisclaimerWidth
        }
        attributionOptions {
          footerAttributionBorderBottomLeftRadius
          footerAttributionBorderBottomRightRadius
          footerAttributionBorderBottomStyle
          footerAttributionBorderBottomWidth
          footerAttributionBorderLeftStyle
          footerAttributionBorderLeftWidth
          footerAttributionBorderRightStyle
          footerAttributionBorderRightWidth
          footerAttributionBorderTopLeftRadius
          footerAttributionBorderTopRightRadius
          footerAttributionBorderTopStyle
          footerAttributionBorderTopWidth
          footerAttributionFontSize
          footerAttributionFontSizeMobile
          footerAttributionFontStyle
          footerAttributionFontWeight
          footerAttributionHorizontalPadding
          footerAttributionLetterSpacing
          footerAttributionLetterSpacingMobile
          footerAttributionLineHeight
          footerAttributionLineHeightMobile
          footerAttributionMarginBottom
          footerAttributionMarginLeft
          footerAttributionMarginRight
          footerAttributionMarginTop
          footerAttributionMobileHorizontalPadding
          footerAttributionMobileMarginBottom
          footerAttributionMobileMarginLeft
          footerAttributionMobileMarginRight
          footerAttributionMobileMarginTop
          footerAttributionMobileVerticalPadding
          footerAttributionTextTransform
          footerAttributionVerticalPadding
          numberFooterAttributionWidth
          rangeFooterAttributionWidth
          unitSelectorFooterAttributionWidth
        }
      }
    }
`;

export default GET_THEME_SETTINGS;

